### ISSUE TITLE
Ubuntu Fix

### ISSUE THREAD

**Issue by skypce** [zagortenay333/conky-Vision#1]
I want contribute with a guide fox fix problems with conky in ubuntu 14.04:
https://sites.google.com/site/conkyfixforubuntu/

Thank you for google Vision it is a great theme.

**Comment by zagortenay333** [comment]
Glad you like it :smile: 

If you mean adding the guide to the README of this repo or similar, then I'm gonna have to reject. This is a conky _theme_, so only bugs/issues related to this theme will be part of this repo.

Bugs related to conky itself should be reported against https://github.com/brndnmtthws/conky

**Comment by skypce** [comment]
ok thank you :D

2015-10-24 17:56 GMT-03:00 zagortenay333 <notifications@github.com>:

**Comment by zagortenay333** [comment]
Ok closing this then.
