### ISSUE TITLE
Issue with conky weather

### ISSUE THREAD

**Issue by Monsieurzik** [zagortenay333/conky-Vision#11]
Hello,

starting the conky i've got these line in terminal : 
`***** Imlib2 Developer Warning ***** :
	This program is calling the Imlib call:

	imlib_context_free();

	With the parameter:

	context

	being NULL. Please fix your program.`

How can i fix it ? 

The settings haven't changed in my conkyrc file. 
Thanks in advance. 

Jonathan

**Comment by zagortenay333** [comment]
What version of conky are you using?

**Comment by Monsieurzik** [comment]
So, i used the backports veriosn of conky, the 1.10 and it's allright now. 

Excuse me for the anoyment.
