### ISSUE TITLE
weather icons not centered

### ISSUE THREAD

**Issue by GolfDeltaFox** [zagortenay333/conky-Vision#12]
After installing and following the instructions, this is what I get. Any help?

![deepinscreenshot_select-area_20170714025932](https://user-images.githubusercontent.com/11540623/28208018-3f4d5722-687b-11e7-9f2d-89402603ffbc.png)

**Comment by zagortenay333** [comment]
Did you edit the conky?

Also, what's the output of the terminal?

**Comment by GolfDeltaFox** [comment]
I have just changed the API key and city ID.
Also, my screen resolution is 3840x2160.
Here's the output:

> conky: desktop window (300002a) is subwindow of root window (105)
> conky: window type - dock
> conky: drawing to created window (0x5200002)
> conky: drawing to double buffer
> conky: forked to background, pid is 1365

**Comment by zagortenay333** [comment]
From your screenshot, the font size of the clock is clearly bigger than in the default. That's what's causing the misalignment. I don't know why your font size is bigger.

Tweak the font size in the conky file until it's right again.
