### ISSUE TITLE
weather icons are not showing

### ISSUE THREAD

**Issue by Northest** [zagortenay333/conky-Vision#13]
I installed all of the requirements (jq, curl, conky-all, lua, libimlib2 etc.) but icons are not showing up. I edited api and location id then started it, everything is working perfect but icons. As i understand from terminal, conky couldn't find the images location so i looked at conkyrc file again and saw that the image locations are wrong, i've entered true locations and run again, this time terminal didn't show me any error, any output, only regular conky working outputs. Everything is fine but still there is no weather icons.
![screenshot from 2017-07-19 15-51-30](https://user-images.githubusercontent.com/12845347/28367590-2954d38c-6c9a-11e7-978c-01865bb95938.png)

**Comment by zagortenay333** [comment]
What's the terminal output. Also turn it off and on again (it works sometimes heh).
