### ISSUE TITLE
Not showing weather information

### ISSUE THREAD

**Issue by echosmart792** [zagortenay333/conky-Vision#16]
Hi !
I'm reinstall Ubuntu 17.10, and reinstall this conky.
All runnung ok, but not display weather information.

https://imgur.com/a/AQpSx

This is my conkyrc file settings for weather: https://imgur.com/a/UYdSk

It's possible to solve this ? Thanks in advance !

**Comment by echosmart792** [comment]
After five minutes show first weather info only

https://imgur.com/a/6jhm1

**Comment by zagortenay333** [comment]
So does it work or does it not work?

**Comment by echosmart792** [comment]
Not work, only first weather data showing other data is 0 (zero)

**Comment by zagortenay333** [comment]
Did you try to kill conky and restart again?
Also, show me the content of the `~/.cache/conky-vision/forecast.json` file.

**Comment by Ehztot** [comment]
hi i have same issue ubuntu.16.04.3 

![2017-11-06 19-35-51](https://user-images.githubusercontent.com/26058269/32437161-cbd0252c-c329-11e7-995b-10ad7835954c.png)

**Comment by zagortenay333** [comment]
@Ehztot  No, you don't have the same issue. You need to install `conky-all` in order to have images.

**Comment by Ehztot** [comment]
thanks! i didn't know that.

**Comment by echosmart792** [comment]
Hi !
This is the file: http://paste.ubuntu.com/25903854/

This is conky results: https://imgur.com/a/RF8JD

**Comment by echosmart792** [comment]
[forecast.zip](https://github.com/zagortenay333/conky-Vision/files/1446850/forecast.zip)

**Comment by echosmart792** [comment]
how to update this 2 folders ??

**Comment by echosmart792** [comment]
I kill conky session and run from terminal:

`brian@BrianPC:~$ conky
conky: desktop window (200018) is subwindow of root window (270)
conky: window type - dock
conky: drawing to created window (0x2a00002)
conky: drawing to double buffer
conky: forked to background, pid is 4584
brian@BrianPC:~$ 
/home/brian/.conky-vision/parse_weather: 78. sor: printf: .62625000000000000000: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: .28125000000000000000: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: 4.70000000000000000000: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: 4.70000000000000000000: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: 3.05375000000000000000: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: 2.30538461538461538461: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: 2.30538461538461538461: érvénytelen szám
/home/brian/.conky-vision/parse_weather: 78. sor: printf: 3.05375000000000000000: érvénytelen szám

`

érvénytelen szám = Invalid number

**Comment by echosmart792** [comment]
https://imgur.com/a/b91Ue

**Comment by zagortenay333** [comment]
Oh you got that printf bug. A commit was pushed to fix it. Are you using the latest commit? (Basically, remove everything and download again if you don't know how to use git.)

**Comment by echosmart792** [comment]
Hi !
I'm dowload again all anr reinstall. After this operation, i hawe weather icons but not display only current temperature. For next 4 days all temperature have 0*C

https://imgur.com/a/m8nPo

This is terminal:
`brian@BrianPC:~$ conky
conky: desktop window (200018) is subwindow of root window (270)
conky: window type - dock
conky: drawing to created window (0x2a00002)
conky: drawing to double buffer
conky: forked to background, pid is 4756
brian@BrianPC:~$ 
/home/brian/.conky-vision/parse_weather: line 83: printf: 1.68500000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 3.40000000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 1.59250000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 3.40000000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 3.11750000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 3.11750000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 4.24625000000000000000: invalid number
/home/brian/.conky-vision/parse_weather: line 83: printf: 4.24625000000000000000: invalid numbe`

**Comment by zagortenay333** [comment]
Show me the content of your `.conkyrc` file.

**Comment by echosmart792** [comment]
Hi !
This is my .conkyrc file:
`conky.config = {

-------------------------------------
--  Generic Settings
-------------------------------------
background=true,
update_interval=1,
double_buffer=true,
no_buffers=true,
imlib_cache_size=0,

draw_shades=false,
draw_outline=false,
draw_borders=false,


-------------------------------------
--  Window Specifications
-------------------------------------
gap_x=0,
gap_y=0,

alignment="middle_middle",

minimum_height=400,
minimum_width=600,

own_window=true,
own_window_type="dock",
own_window_transparent=true,
own_window_hints="undecorated,below,sticky,skip_taskbar,skip_pager",

own_window_argb_visual=true,
own_window_argb_value=0,


-------------------------------------
--  Text Settings
-------------------------------------
use_xft=true,
xftalpha=1,
font="Droid Sans:size=10",
text_buffer_size=256,
override_utf8_locale=true,


-------------------------------------
--  Color Scheme
-------------------------------------
default_color='FFFFFF',

color0='FFFFFF', -- clock
color1='FFFFFF', -- date
color2='FFFFFF', -- current temperature
color3='FFFFFF', -- high tempratures
color4='FFFFFF', -- low tempratures
color5='FFFFFF', -- days


-------------------------------------
--  Icon Sources
-------------------------------------
template0='~/.conky-vision/#fff__32',  --  today
template1='~/.conky-vision/#fff__32',  --  +1day
template2='~/.conky-vision/#fff__32',  --  +2days
template3='~/.conky-vision/#fff__32',  --  +3days
template4='~/.conky-vision/#fff__32',  --  +4days


-------------------------------------
--  API Key
-------------------------------------
template6="2edc4ae6826281a498d8ff3f96161ded",


-------------------------------------
--  City ID
-------------------------------------
template7="679452",


-------------------------------------
--  Temp Unit (default, metric, imperial)
-------------------------------------
template8="metric",


-------------------------------------
--  Locale (e.g. "es_ES.UTF-8")
--  Leave empty for default
-------------------------------------
template9="hu_HU.UTF-8"

}


---------------------------------------------------
---------------------------------------------------


conky.text = [[
\
\
\
\
${execi 300 ~/.conky-vision/get_weather ${template6} ${template7} ${template8} ${template9}}\
\
\
\
\
${font Poiret One:weight=Light:size=96}${color0}\
${alignc}${time %H:%M}\
${font}${color}
\
\
\
\
${font Poiret One:weight=Light:size=28}${color1}\
${voffset 30}\
${alignc}${execi 300 LANG=${template9} LC_TIME=${template9} date +"%A, %B %d"}\
${font}${color}
\
\
\
\
${font Poiret One:size=18}${color2}\
${voffset 36}\
${goto 60}${execi 300 jq .main.temp ~/.cache/conky-vision/weather.json | awk '{print int($1+0.5)}' # round num}°\
${font}${color}\
\
\
\
\
${font Poiret One:size=12}${color3}\
${goto 164}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_max' '1'}°\
${goto 272}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_max' '2'}°\
${goto 378}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_max' '3'}°\
${goto 484}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_max' '4'}°\
${font}${color}\
\
\
\
\
${font Poiret One:size=12}${color4}\
${voffset 52}\
${goto 218}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_min' '1'}°\
${goto 324}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_min' '2'}°\
${goto 430}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_min' '3'}°\
${goto 536}${execi 300 ~/.conky-vision/parse_weather 'avg' '.main.temp_min' '4'}°\
${font}${color}
\
\
\
\
${font Poiret One:size=14}${color5}\
${voffset 20}\
${goto 76}${execi 300 LANG=${template9} LC_TIME=${template9} date +%^a}\
${goto 182}${execi 300 LANG=${template9} LC_TIME=${template9} date -d +1day +%^a}\
${goto 288}${execi 300 LANG=${template9} LC_TIME=${template9} date -d +2days +%^a}\
${goto 394}${execi 300 LANG=${template9} LC_TIME=${template9} date -d +3days +%^a}\
${goto 500}${execi 300 LANG=${template9} LC_TIME=${template9} date -d +4days +%^a}\
${font}${color}
\
\
\
\
${execi 300 cp -f ${template0}/$(jq .weather[0].id ~/.cache/conky-vision/weather.json).png ~/.cache/conky-vision/current.png}${image ~/.cache/conky-vision/current.png -p 72,266 -s 32x32}\
${execi 300 cp -f ${template1}/$(~/.conky-vision/parse_weather 'first' '.weather[0].id' '1').png ~/.cache/conky-vision/forecast-1.png}${image ~/.cache/conky-vision/forecast-1.png -p 178,266 -s 32x32}\
${execi 300 cp -f ${template2}/$(~/.conky-vision/parse_weather 'first' '.weather[0].id' '2').png ~/.cache/conky-vision/forecast-2.png}${image ~/.cache/conky-vision/forecast-2.png -p 284,266 -s 32x32}\
${execi 300 cp -f ${template3}/$(~/.conky-vision/parse_weather 'first' '.weather[0].id' '3').png ~/.cache/conky-vision/forecast-3.png}${image ~/.cache/conky-vision/forecast-3.png -p 390,266 -s 32x32}\
${execi 300 cp -f ${template4}/$(~/.conky-vision/parse_weather 'first' '.weather[0].id' '4').png ~/.cache/conky-vision/forecast-4.png}${image ~/.cache/conky-vision/forecast-4.png -p 496,266 -s 32x32}\
]]`

**Comment by zagortenay333** [comment]
Oops, I meant your `~/.conky-vision/parse_weather` file.

**Comment by echosmart792** [comment]
This is parse_weather file:

`#!/bin/bash

#Avoid errors on printf with systems with a locale that use the comma instead of
#the dot for floats
LANG=C

set -eu

forecast=~/".cache/conky-vision/forecast.json"

get_time () {
    local idx="$1"

    time=$(jq ".list[$idx].dt_txt" "$forecast")
    time="${time##* }"
    time="${time%%\"}"

    echo "$time"
}

find_position () {
    local day="$1"
    local pos=0
    local idx=0
    local time=""

    [[ $day == 0 ]] && echo "$idx" && return

    while true; do
        time=$(get_time "$idx")

        [[ $time == "00:00:00" ]] && ((pos++))

        [[ $time == "null" ]] && break
        [[ $pos == "$day" ]] && break

        ((idx++))
    done

    echo "$idx"
}

# Currently, the free accounts on openweathermap.org only get a 5 day forecast
# with data records for every 3 hours instead of the average value for the day,
# so we have to compute the average temp_min, temp_max, etc manually.
get_avg_property () {
    local res=0

    local prop="$1"
    local day="$2"

    local idx
    idx=$(find_position "$day")

    local prop_num=0
    local time=0
    local it=0

    while true; do
        [[ $time == "null" ]] && break

        it=$(jq ".list[$idx]$prop" "$forecast")

        it="$res+$it"
        res=$(bc -l <<< "$it")

        (( prop_num++ ))
        (( idx++ ))

        time=$(get_time "$idx")

        # The records for every 3 hours are dumped in an array with no
        # indication to which day they belong.
        # The first record of each day (except today) is calculated at time
        # '00:00:00', so we use that to know when a new day starts.
        [[ $time == "00:00:00" ]] && break
    done

    res="$(bc -l <<< "$res/$prop_num")"

    [[ $res == "null" ]] && echo $res && return

    printf %.0f $res
}

# Certain values cannot be averaged (e.g., the weather description).
# In that case we just use the value from the first record for that day.
get_first_property () {
    local res=0

    local prop="$1"
    local day="$2"

    local idx
    idx=$(find_position "$day")

    res=$(jq ".list[$idx]$prop" "$forecast")

    [[ $res == "null" ]] && echo $res && return

    printf %.0f $res
}

main () {
    type="$1"
    prop="$2"
    day="$3"

    if [[ $type == "avg" ]] ; then
        echo "$(get_avg_property "$2" "$3")"
    elif [[ $type == "first" ]] ; then
        echo "$(get_first_property "$2" "$3")"
    fi
}

[[ -r $forecast ]] && main "$@"`

**Comment by zagortenay333** [comment]
Could you try downloading again? I think it should be fixed now.

**Comment by echosmart792** [comment]
Hi !
I'm downloaded today last version, but same error: https://imgur.com/a/nJhR6

**Comment by zagortenay333** [comment]
Try again. I made another commit. And make sure that you update that `.conky-vision` folder.

**Comment by echosmart792** [comment]
I trying again with new download...
I'm install with install script, but error again, other error 
https://imgur.com/a/YwZun

**Comment by zagortenay333** [comment]
Why are you root? The permissions are wonky then.

**Comment by echosmart792** [comment]
i'm delete conky-vision folder from home folder, and conkyrc file.

Reinstall all from new download, but hawe same errors: https://imgur.com/a/u5KwO

**Comment by zagortenay333** [comment]
Try again.. Make sure to again update that `.conky-vision` folder

**Comment by echosmart792** [comment]
Thanks !!! You are great !!!!
Working all ok !!
https://imgur.com/a/BkmOP

Thanks for your support !

**Comment by echosmart792** [comment]
Thanks !!! You are great !!!!
Working all ok !!
https://imgur.com/a/BkmOP

Thanks for your support !

**Comment by echosmart792** [comment]
Thanks !!! You are great !!!!
Working all ok !!
https://imgur.com/a/BkmOP

Thanks for your support !

**Comment by echosmart792** [comment]
Thanks !!! You are great !!!!
Working all ok !!
https://imgur.com/a/BkmOP

Thanks for your support !

**Comment by echosmart792** [comment]
Thanks !!! You are great !!!!
Working all ok !!
https://imgur.com/a/BkmOP

Thanks for your support !

**Comment by echosmart792** [comment]
Thanks !!! You are great !!!!
Working all ok !!
https://imgur.com/a/BkmOP

Thanks for your support !

**Comment by zagortenay333** [comment]
Cheers.
