### ISSUE TITLE
Can't read generated images?

### ISSUE THREAD

**Issue by EricTill** [zagortenay333/conky-Vision#2]
First of all, thanks for the cool theme.

I just tried regenerating all of the pngs because I wanted them to be in black.

render-pngs.sh crashed because it couldn't handle the "#" in the directory name (although I'm kind of ashamed to admit that I wasn't able to fix it). Whatever - I only wanted one color, so I just copied the directory by hand.

But now I'm pointing at it from the conkyrc file and I don't see any icons! When I open the pngs myself they look just fine! Any clue what's going on? I feel like I'm taking crazy pills because I *know* the paths are correct!

**Comment by zagortenay333** [comment]
Hmm, most probably the hash needs to be escaped in the filename. I don't seem to have any issues on my system. Try using the color `black` instead of `#000000`. If that works, I'll update the script to fix this.
Also, can I see the error when the script crashed?

Also, if you directory has a `#` in it's name, then inside the `.conkyrc` it must be escaped with a backlash as well; otherwise, conky reads it as a comment.

**Comment by EricTill** [comment]
Thanks for getting back to me so quickly! What comes next might be a little disjointed because I'm pretty tired... But I thought I'd give you plenty of info.

I think something's wrong my with pngs.

I realized there were problems with the hash. In fact the first thing I tried was just moving the "#000000" directory into conky-vision-icons/ manually. 

I'm trying to run this from ~/.config/conky/ folder - I changed the pathnames in the conky configuration file and the render-pngs.sh file, and the only path-type error I get is from this line:

`# Inkscape doesn't work well with dir paths
    # Move folder manually
    mv "$COLOR_DIR" "$PNG_DEST"`

With this error message:
`mv: cannot stat ‘~/.config/conky/black’: No such file or directory`

But that file definitely exists when I look!

Maybe this is important information: the script crashed before running this line:
`# Revert edit of svg's before next iteration or EXIT
sed -i "s/<path fill=\"$color\"/<path/" $SOURCE`

Even when I use "black" for the color it won't work.

The conky script is definitely able to find the generated pngs because it doesn't generate any errors (but does when I put in a bogus filename).

So - what's the problem? When I run the generation script with "white" as the color everything works fine (after I manually move the directory). "red" doesn't work. Other colors don't seem to work. So maybe something's wrong with the generated red and black pngs? What do you think I should look for?

**Comment by zagortenay333** [comment]
Ah, I see you edited the `PNG_DEST` variable. I forgot to ensure that this dir exists if it's changed.

Fixed with fda06f2d035754463243c3b8d3a9fadea3060b89

**Comment by zagortenay333** [comment]
Can I close this?

**Comment by EricTill** [comment]
Thanks!
