### ISSUE TITLE
Icons don't appear

### ISSUE THREAD

**Issue by perru** [zagortenay333/conky-Vision#4]
With the last conky update, Icons don't appear anymore.

**Comment by zagortenay333** [comment]
Always give the terminal output when you report a bug like this.

**Comment by perru** [comment]
> conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
> conky: Assuming it's in old syntax and attempting conversion.
> conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
> conky: desktop window (2b7) is root window
> conky: window type - normal
> conky: drawing to created window (0x800002)
> conky: drawing to double buffer
> conky: forked to background, pid is 2934
> conky: Unable to load image '/home/perru/.cache/current.png'
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> : Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
>

**Comment by perru** [comment]
Sure :

> conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
> conky: Assuming it's in old syntax and attempting conversion.
> conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
> conky: desktop window (2b7) is root window
> conky: window type - normal
> conky: drawing to created window (0x800002)
> conky: drawing to double buffer
> conky: forked to background, pid is 2934
> conky: Unable to load image '/home/perru/.cache/current.png'
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> : Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
>

**Comment by perru** [comment]
Sure :

> conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
> conky: Assuming it's in old syntax and attempting conversion.
> conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
> conky: desktop window (2b7) is root window
> conky: window type - normal
> conky: drawing to created window (0x800002)
> conky: drawing to double buffer
> conky: forked to background, pid is 2934
> conky: Unable to load image '/home/perru/.cache/current.png'
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> : Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
>

**Comment by perru** [comment]
Sure :

> conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
> conky: Assuming it's in old syntax and attempting conversion.
> conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
> conky: desktop window (2b7) is root window
> conky: window type - normal
> conky: drawing to created window (0x800002)
> conky: drawing to double buffer
> conky: forked to background, pid is 2934
> conky: Unable to load image '/home/perru/.cache/current.png'
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> : Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
>

**Comment by perru** [comment]
Sure :

> conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
> conky: Assuming it's in old syntax and attempting conversion.
> conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
> conky: desktop window (2b7) is root window
> conky: window type - normal
> conky: drawing to created window (0x800002)
> conky: drawing to double buffer
> conky: forked to background, pid is 2934
> conky: Unable to load image '/home/perru/.cache/current.png'
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> : Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
>

**Comment by perru** [comment]
```
conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
conky: desktop window (2b7) is root window
conky: window type - normal
conky: drawing to created window (0x800002)
conky: drawing to double buffer
conky: forked to background, pid is 2934
conky: Unable to load image '/home/perru/.cache/current.png'
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
: Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type

```

**Comment by perru** [comment]
Sure :

```
conky: Syntax error (/home/perru/.conkyrc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: Invalid value 'undecorate' for setting 'own_window_hints'. Valid values are: 'undecorated', 'below', 'above', 'sticky', 'skip_taskbar', 'skip_pager'.
conky: desktop window (2b7) is root window
conky: window type - normal
conky: drawing to created window (0x800002)
conky: drawing to double buffer
conky: forked to background, pid is 2934
conky: Unable to load image '/home/perru/.cache/current.png'
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png'cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
: Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer '/home/perru/.conky-vision-icons//null.png': Aucun fichier ou dossier de ce type

```

**Comment by perru** [comment]
Sure :
http://pastebin.com/Jsud9zhE

**Comment by perru** [comment]
Sure :
http://pastebin.com/Jsud9zhE

**Comment by zagortenay333** [comment]
This is a duplicate of #3 . You have the version `1.10.x`. This conky is made for `1.9.x`.
