### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anoniem700** [zagortenay333/conky-Vision#5]
I used your code, then tried adding a calendar to it with gcalcli.
Somehow I cannot use ${offset [num]} on it, I have been trying different things and searching around for at least 8 hours now and you are my last hope...

Here's the pastebin of my .conkyrc http://pastebin.com/f2bVY0HD , The last line is where my problem is, currently the offset is set in the line above but it used to be right in front of execpi.

I'd really appreciate your help.

**Comment by zagortenay333** [comment]
There is `offset` for horizontal motion and `voffset` for vertical motion. Not sure which one you mean.

Also, the line prior to your calendar has a backslash at the end of it, which means your calendar is drawn on the same line as that one. So, put a newline above the calendar.

This should work http://pastebin.com/vMAFRJTJ

**Comment by anoniem700** [comment]
I meant offset voffset works fine, but somehow offset doesn't work at
all(goto doesn't work either), this goes for all execi I have noticed.

**Comment by zagortenay333** [comment]
How is `goto` not working. Every line in this conky uses it. :confused: 

Does the conky I gave you work?

**Comment by anoniem700** [comment]
Yeah, that's why I don't have any clue why it doesn't work... All lines
work except that one.

The conky you gave me works as it uses voffset, which works fine. offset
and goto don't work for whatever reason :l (So I can only move it
vertically, not horizontally.. which I need it to).

**Comment by zagortenay333** [comment]
What is this gcalcli you are using anyway? Maybe it is the culprit.

**Comment by anoniem700** [comment]
gcalcli (google calendar command line interface)
https://github.com/insanum/gcalcli

I suppose it can't be the problem though since it get's executed like any
command by conky and the output printed on screen. Which should just work
with offset right?

**Comment by zagortenay333** [comment]
Welp no clue then. :confused: 

Gonna close this since it's unrelated to this conky theme.
