### ISSUE TITLE
No weather icons are displaying.Get errors

### ISSUE THREAD

**Issue by ekatsaros** [zagortenay333/conky-Vision#6]
Hi,

When i run conky i get the following errors.

Conky: forked to background, pid is 2498
evangelos@elementaryOS:~$ 
Conky: desktop window (100001c) is subwindow of root window (165)
Conky: window type - normal
Conky: drawing to created window (0x3000002)
Conky: drawing to double buffer
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat ‘/home/evangelos/.conky-vision-icons/#fff__32/.png’: No such file or directory
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat ‘/home/evangelos/.conky-vision-icons/#fff__32/.png’: No such file or directory
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat ‘/home/evangelos/.conky-vision-icons/#fff__32/.png’: No such file or directory
parse error: Invalid numeric literal at line 1, column 7
cp: cannot stat ‘/home/evangelos/.conky-vision-icons/#fff__32/.png’: No such file or directory

any ideas what might be wrong?

**Comment by zagortenay333** [comment]
You probably didn't add the API key and city inside the `.conkyrc` file.

**Comment by ekatsaros** [comment]
I did! in template 6 and 7 API Key and City ID Respectively.Only Template 9 left blank for default locale.

**Comment by zagortenay333** [comment]
Which version of conky are you running?

Poost a pastebin link to your `.conkyrc` if you don't mind.

**Comment by ekatsaros** [comment]
It's working the API key was wrong.
Thank you.
