### ISSUE TITLE
Icons don't appear - ${image}

### ISSUE THREAD

**Issue by Gnappa** [zagortenay333/conky-Vision#7]
Hello, I've used your files on ubuntu 14.04 without problems.
Now, I have ubuntu 16.04 and conky 1.10.1 , I downloaded the new version of your .conkyrc and configured it, it works except the icons: you can read "$image".
![screen](https://cloud.githubusercontent.com/assets/21132608/17824518/cab30a1c-6662-11e6-8685-7b00bca7f969.png)

this is the output from the terminal:
`conky -c .conkyrc_vision 
conky: desktop window (2600015) is subwindow of root window (4a7)
conky: window type - normal
conky: drawing to created window (0x2e00002)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: forked to background, pid is 31156
`
It can be solved?
Thank you

**Comment by zagortenay333** [comment]
If you are on ubuntu, install `conky-all`.

**Comment by Gnappa** [comment]
That works perfectly, thank you
