### ISSUE TITLE
Can't change color of weather icons

### ISSUE THREAD

**Issue by fabianbormann** [zagortenay333/conky-Vision#8]
Hi, your conky theme looks so great and the documentation is very completely and easy to understand/reproduce :+1: 

I have maybe some kind of first world Problem.. I want to change the weather icon color, but conky does not update the color correctly :/ 

Like in your description I used the render-png script to produce new png icons. I placed them into the ~/.conky-vision-icons directory.

I updated the .conkyrc:

```bash
-------------------------------------
--  Icon Sources
-------------------------------------
template0='~/.conky-vision-icons/#3696c9__32',  --  today
template1='~/.conky-vision-icons/#3696c9__32',  --  +1day
template2='~/.conky-vision-icons/#3696c9__32',  --  +2days
template3='~/.conky-vision-icons/#3696c9__32',  --  +3days
template4='~/.conky-vision-icons/#3696c9__32',  --  +4days
```

and the new icons were automatically correctly copied to ~/.cache folder
but the icon color on my screen is still white. If I edit the current.png icon with gimp and remove the half of that image, it conky updates the screen with the new "half" icon but it's still white. 

I'm using debian jessie with conky 1.10.5.

Can you help me?

Thanks!

![bildschirmfoto](https://cloud.githubusercontent.com/assets/1525818/20301015/00ae1a04-ab22-11e6-8db5-267ab7328a79.png)

**Comment by zagortenay333** [comment]
Did you try to kill conky and restart again?

**Comment by zagortenay333** [comment]
Also, what's the terminal output?

**Comment by fabianbormann** [comment]
Yes, I restarted my PC and also after kill conky and restart it again the icon color is still white

```zsh
>>> sudo killall conky

>>> conky
conky: desktop window (1a00003) is subwindow of root window (1ea)
conky: window type - dock
conky: drawing to created window (0x3200002)
conky: drawing to double buffer
conky: forked to background, pid is 6368
```

**Comment by zagortenay333** [comment]
Umm, did you update the correct `.conkyrc` file (the one in the home directory)?

**Comment by zagortenay333** [comment]
Ah, I know what the issue is...

It's the same old problem conky has with images and argb. Basically unless you use white icons you are gonna have trouble with it. The only workaround is to not use argb.

Set:
```
own_window_argb_visual=false,
```
Or comment it out.

The problem with that is that on some DE's not using argb will cause other problems, but since you are on xfce you shouldn't have any issues.

**Comment by fabianbormann** [comment]
Yes great ! Set ```own_window_argb_visual=false``` solved my problem :+1:
